
import NavBar from "@/components/navBar/NavBar";
import "./globals.css"
import { tourney } from "@/fonts"
import type { Metadata } from "next";
import Footer from "@/components/footer/fotter";
import AboutMe from "@/components/aboutMe/aboutMe";


export const metadata: Metadata = {
  title: "Christian Rugna",
  description: "Generated by Christian Rugna",
  icons: "LogoPortfolio.svg"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black min-h-screen flex flex-col">
        <header className="fixed top-0 w-full z-10">
          <NavBar />
        </header>
        <main className="pt-14 flex-1">
          <AboutMe />
          {children}
        </main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}